### ISSUE TITLE
HTML markup in a comment appears to break the api

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/api.silverstripe.org#63] opened 2017-11-30 19:23 UTC
An example is: http://api.silverstripe.org/4/SilverStripe/Forms/DropdownField.html

It appears to be trying to render the HTML inside the comment, which is then making the rest of the page unusable.

**Comment by robbieaverill** [comment] 2017-11-30 20:28
Thanks for reporting. This is a duplicate of https://github.com/silverstripe/api.silverstripe.org/issues/55

**Closed by robbieaverill** 2017-11-30 20:28 UTC
